[versions]
kotlin = "1.9.22"
ksp = "1.9.23-1.0.19"
hilt = "2.51"
androidHilt = "1.2.0"
androidGradlePlugin = "8.3.0"

compose = "2024.03.00"
appcompat = "1.6.1"
ktx = "1.12.0"
activityCompose = "1.8.2"
material3 = "1.2.1"
lifecycle = "2.7.0"
navigation = "2.7.7"
room = "2.6.1"
datastore = "1.0.0"

retrofit = "2.9.0"
moshi = "1.15.0"
okhttp = "4.12.0"

coil = "2.6.0"

junit = "4.13.2"
coroutine-test = "1.8.0"
mockk = "1.13.4"

junitAndroidExt = "1.1.5"
espresso = "3.5.1"
testRunner = "1.5.2"
testRules = "1.5.0"


[libraries]
android-compose-bom = { group = "androidx.compose", name = "compose-bom",  version.ref = "compose" }
android-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
android-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
android-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
android-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
android-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref= "lifecycle" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref= "lifecycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref= "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref= "lifecycle" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

navigation-compose = { group = "androidx.navigation", name = "navigation-compose" , version.ref = "navigation"}
navigation-testing = { group = "androidx.navigation", name = "navigation-testing" , version.ref = "navigation"}

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }

moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
dagger-dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "hilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
android-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidHilt" }

coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }


junit = { group = "junit", name = "junit", version.ref = "junit" }

coroutine-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutine-test" }

mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }

android-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitAndroidExt" }
android-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
android-test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
android-test-rules = { group = "androidx.test", name = "rules", version.ref = "testRules" }



[plugins]
kotlin-android = {id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

